import type { Article } from "@/components/article-card";

export const mockTimelineArticles: Article[] = [
	{
		id: "1",
		title: "Getting Started with Next.js 15 and React Server Components",
		description:
			"A comprehensive guide to building modern web applications with the latest features in Next.js 15, including server components and streaming.",
		status: "published",
		createdAt: new Date("2024-10-10"),
		publishedAt: new Date("2024-10-10"),
		views: 12534,
		readTime: 8,
		completionRate: 87,
		tags: ["Next.js", "React", "Web Development"],
		coverImage: undefined,
	},
	{
		id: "2",
		title: "Mastering TypeScript: Advanced Patterns and Best Practices",
		description:
			"Deep dive into TypeScript's type system, exploring advanced patterns like conditional types, mapped types, and template literal types.",
		status: "published",
		createdAt: new Date("2024-10-08"),
		publishedAt: new Date("2024-10-08"),
		views: 8921,
		readTime: 12,
		completionRate: 92,
		tags: ["TypeScript", "JavaScript", "Programming"],
	},
	{
		id: "3",
		title: "Building Scalable APIs with tRPC and Prisma",
		description:
			"Learn how to create type-safe APIs that scale with your application using tRPC and Prisma ORM.",
		status: "published",
		createdAt: new Date("2024-10-05"),
		publishedAt: new Date("2024-10-05"),
		views: 15432,
		readTime: 15,
		completionRate: 78,
		tags: ["tRPC", "Prisma", "API", "Backend"],
	},
	{
		id: "4",
		title: "The Future of Web Animation: Framer Motion vs CSS",
		description:
			"Comparing modern animation libraries and techniques to create smooth, performant animations in your React applications.",
		status: "scheduled",
		createdAt: new Date("2024-10-15"),
		scheduledFor: new Date("2025-10-20T14:30:00"),
		views: 0,
		readTime: 10,
		completionRate: 0,
		tags: ["Animation", "Framer Motion", "CSS", "React"],
	},
	{
		id: "5",
		title: "Optimizing React Performance: A Deep Dive",
		description:
			"Techniques and strategies for optimizing React applications, including memoization, code splitting, and lazy loading.",
		status: "published",
		createdAt: new Date("2024-10-01"),
		publishedAt: new Date("2024-10-01"),
		views: 19834,
		readTime: 11,
		completionRate: 85,
		tags: ["React", "Performance", "Optimization"],
	},
	{
		id: "6",
		title: "Understanding Database Indexing for Better Performance",
		description:
			"A practical guide to database indexing strategies that can significantly improve your application's query performance.",
		status: "scheduled",
		createdAt: new Date("2024-10-14"),
		scheduledFor: new Date("2025-10-22T09:00:00"),
		views: 0,
		readTime: 9,
		completionRate: 0,
		tags: ["Database", "SQL", "Performance"],
	},
	{
		id: "7",
		title: "Modern CSS: Grid, Flexbox, and Container Queries",
		description:
			"Master modern CSS layout techniques to create responsive, flexible designs without relying on frameworks.",
		status: "published",
		createdAt: new Date("2024-09-28"),
		publishedAt: new Date("2024-09-28"),
		views: 11256,
		readTime: 7,
		completionRate: 91,
		tags: ["CSS", "Web Design", "Responsive"],
	},
	{
		id: "7a",
		title: "Outdated Tutorial: jQuery Best Practices (2015)",
		description:
			"This article contains outdated information and has been deactivated. Please refer to our modern JavaScript guides instead.",
		status: "draft",
		createdAt: new Date("2024-09-15"),
		publishedAt: new Date("2024-09-15"),
		views: 5432,
		readTime: 6,
		completionRate: 45,
		tags: ["jQuery", "Legacy", "Deprecated"],
	},
	{
		id: "8",
		title: "Building Real-time Applications with WebSockets",
		description:
			"Learn how to implement real-time features in your applications using WebSockets and modern frameworks.",
		status: "published",
		createdAt: new Date("2024-09-25"),
		publishedAt: new Date("2024-09-25"),
		views: 14567,
		readTime: 13,
		completionRate: 83,
		tags: ["WebSockets", "Real-time", "Backend"],
	},
	{
		id: "9",
		title: "Introduction to Machine Learning with Python",
		description:
			"A beginner-friendly introduction to machine learning concepts and practical implementation using Python and scikit-learn.",
		status: "scheduled",
		createdAt: new Date("2024-10-16"),
		scheduledFor: new Date("2025-10-25T16:45:00"),
		views: 0,
		readTime: 16,
		completionRate: 0,
		tags: ["Machine Learning", "Python", "AI"],
	},
	{
		id: "10",
		title: "Secure Authentication Patterns in Modern Web Apps",
		description:
			"Best practices for implementing secure authentication and authorization in web applications using JWT and OAuth.",
		status: "published",
		createdAt: new Date("2024-09-20"),
		publishedAt: new Date("2024-09-20"),
		views: 22145,
		readTime: 14,
		completionRate: 89,
		tags: ["Security", "Authentication", "Web Development"],
	},
];

